<?php
/**
 * Created by PhpStorm.
 * User: bursak
 * Date: 10/7/16
 * Time: 7:54 PM
 */

namespace Views;

use Core\Base_View;

class Home_View extends Base_View {

  function index() {
  }

  function index_sub( $data ) {
  }

  function sub_template()
  {
    $this->concat_content();
    $layout = $this->get_layout();
  }

  function get_header() {
    $header = parent::get_header(); // TODO: Change the autogenerated stub
    return $header . ' changed';
  }

}