<?php
/**
 * Created by PhpStorm.
 * User: bursak
 * Date: 10/7/16
 * Time: 7:54 PM
 */

namespace Views;

use Core\Base_View;
use helpers\GlobalData;

class Home_View extends Base_View {

  function index() {
    $this->set_date( GlobalData::get( 'site_data' ) );
  }

  function index_sub( $data ) {
  }

  function sub_template()
  {
  }

  function get_header() {
    $header = parent::get_header(); // TODO: Change the autogenerated stub
    return $header . ' changed';
  }

}